### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/stock#216]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] stock_picking_state
- [ ] stock_ux
- [ ] stock_ean128
- [ ] stock_lot_information
- [ ] stock_picking_ean128_report
- [ ] stock_batch_picking_ux
- [ ] stock_voucher
- [ ] stock_picking_labels
- [ ] stock_picking_partner_editable
- [ ] stock_request_ux
- [ ] stock_analytic_tag
- [ ] stock_removal_by_location_priority
- [ ] stock_picking_responsible
- [ ] location_security
