### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/stock#75]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] location_security
- [ ] stock_ean128
- [ ] stock_inventory_negative_line
- [ ] stock_inventory_preparation_filter
- [ ] stock_inventory_require_lot
- [ ] stock_lot_information
- [ ] stock_picking_control
- [ ] stock_picking_ean128_report
- [ ] stock_picking_labels
- [ ] stock_picking_list
- [ ] stock_picking_partner_editable
- [ ] stock_picking_responsible
- [ ] stock_picking_state
- [ ] stock_procurement_request
- [ ] stock_traceability_report
- [ ] stock_transfer_restrict_lot
- [ ] stock_usability
- [ ] stock_usability_batch_picking
- [ ] stock_usability_quant_manual_assign
- [ ] stock_voucher
- [ ] stock_warehouse_edit
